// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CarInsuranceTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void carInsurance_25and3and0_ValidData()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2422, 1392);
        //Act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0B8");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("226-866-5623");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("rutvik@GMAIL.COM");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //Assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2500"));
        }
    }
    [Test]
    public void carInsurance_25and3and0_FirstNameOmitted()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2493, 1392);
        //Act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("168 King Street");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Pune");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2I 0N9");
        driver.FindElement(By.Id("phone")).SendKeys("225-696-7899");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
          //  var element = driver.FindElement(By.tagName("body"));
          //  Actions builder = new Actions(driver);
          //  builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("firstName-error")).Text, Is.EqualTo("First Name is required"));
    }
    [Test]
    public void carInsurance_5and0_AgeOmitted()
    {   //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhohj");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2R 5J9");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("555-999-6523");
        driver.FindElement(By.Id("email")).SendKeys("rutvik@gmail.com");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".card-body")).Click();
        //assert
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void carInsurance_25and3and1_AddressOmitted()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("city")).SendKeys("waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2h 2k0");
        driver.FindElement(By.Id("phone")).SendKeys("222-344-2222");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
           // var element = driver.FindElement(By.tagName("body"));
           /// Actions builder = new Actions(driver);
           // builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("address-error")).Text, Is.EqualTo("Address is required"));
    }
    [Test]
    public void carInsurance_27and2and0_CityOmitted()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2J 9O0");
        driver.FindElement(By.Id("phone")).SendKeys("222-123-1233");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("2");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
          //  var element = driver.FindElement(By.tagName("body"));
         //   Actions builder = new Actions(driver);
        //builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("body")).Click();
        Assert.That(driver.FindElement(By.Id("city-error")).Text, Is.EqualTo("City is required"));
    }
    [Test]
    public void carInsurance_26and3and0_LastNameOmitted()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("address")).SendKeys("168 King st");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0B6");
        driver.FindElement(By.Id("phone")).SendKeys("226-889-6045");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("rutvik@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("26");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        //assert
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            //var element = driver.FindElement(By.tagName("body"));
            //Actions builder = new Actions(driver);
           // builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("lastName-error")).Text, Is.EqualTo("Last Name is required"));
    }
    [Test]
    public void carInsurance_27and3and0_InvalidPhoneNo()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2K 0J8");
        driver.FindElement(By.Id("phone")).SendKeys("2244123111");
        driver.FindElement(By.Id("email")).SendKeys("rutvik@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void carInsurance_28and3and0_InvalidEmailId()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2K 0N4");
        driver.FindElement(By.Id("phone")).SendKeys("222-555-6832");
        driver.FindElement(By.CssSelector(".col-md-8")).Click();
        driver.FindElement(By.Id("email")).SendKeys("Must be a valid email address");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void carInsurance_30and0and0_ZeroExp()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2R 4J8");
        driver.FindElement(By.Id("phone")).SendKeys("222-411-1231");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4000"));
        }
    }
    [Test]
    public void carInsurance_30and3and4_FourFaults()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2T 6J0");
        driver.FindElement(By.Id("phone")).SendKeys("212-222-1231");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void carInsurance_32and3and0_reduction25rate()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("123 King");
        driver.FindElement(By.Id("city")).SendKeys("waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("K9L 0O7");
        driver.FindElement(By.Id("phone")).SendKeys("212-123-1233");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("32");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1875"));
        }
    }
    [Test]
    public void carInsurance_35and10and0_TenYearExp()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("1568 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("U8J 0K9");
        driver.FindElement(By.Id("phone")).SendKeys("222-423-1233");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1350"));
        }
    }
    [Test]
    public void carInsurance_35and17and1_InvalidPostalCode()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King st");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2J 9U7");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("222-444-6745");
        driver.FindElement(By.Id("email")).SendKeys("rutvik@gmail.com");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2J123");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("17");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("postalCode-error")).Click();
        //assert
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void carInsurance_37and8_NumberOfFaultsOmitted()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutviki");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N4H 9L9");
        driver.FindElement(By.Id("phone")).SendKeys("122-123-1233");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.CssSelector(".form-group:nth-child(4) > label")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void carInsurance_45and0_DrivingExpOmitted()
    {
        //arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(2560, 1392);
        //act
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rutvik");
        driver.FindElement(By.Id("lastName")).SendKeys("Bhoj");
        driver.FindElement(By.Id("address")).SendKeys("168 King");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N4T 6A0");
        driver.FindElement(By.Id("phone")).SendKeys("222-444-5894");
        driver.FindElement(By.Id("email")).SendKeys("bhoj@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        //assert
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
          //  var element = driver.FindElement(By.tagName("body"));
          //  Actions builder = new Actions(driver);
            //builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector(".card-body")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
}
